[package]
name = "qubosat"
version = "0.1.0"
authors = ["hysok2"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
varisat = "0.2.1"
clap = { version = "3.1.10", features = ["derive"] }

